version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/keycloak
      SPRING_DATASOURCE_USERNAME: keycloak
      SPRING_DATASOURCE_PASSWORD: keycloak
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - 8081:8080
    networks:
      - app-network
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:13.2
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
